spring:
  application:
    name: expensetracker
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/expense_tracker?useTimeZone=true&serverTimezone=UTC
    username: root
    password: chosen1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false